blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/4Source/obsidian-plugin-template/discussions/new/choose
    about: Please ask and answer questions here.
