name: Continuous Integration

on: 
  pull_request:
    branches:
      - master
    paths: 
      - 'src/**'
  push: 
    branches:
      - master
    paths: 
      - 'src/**'
  workflow_dispatch:

jobs:
  log: 
    name: Log
    runs-on: ubuntu-latest

    steps: 
      - name: Log event
        run: echo ${{ github }}

  test:
    name: Run unit tests
    if: github.event.pull_request.merged == true
    runs-on: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    strategy: 
      matrix:
        node-version: ["18.x"]

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  lint:
    name: Run linter
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run linter
        run: npm run lint

  build: 
    name: Build Plugin
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      
      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

  version:
    name: Version Bump 
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && ${{ github.event_name == 'push' }}
    permissions: 
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Bump version
        uses: 4Source/version-control-action@v1
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repository:  ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          tag_prefix: ''
          dry_run: true